services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    volumes:
      - redis_data:/data

  backend:
    platform: linux/arm64
    build:
      context: ./backend
      dockerfile: "${BACKEND_DOCKERFILE}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/backend
      - ./frontend/src/data:/frontend/src/data
      - ./shell.py:/shell.py
      - ./data:/data
    environment:
      - FLASK_APP=run.py
      - REDIS_URL=redis://redis:${REDIS_PORT}/0
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/frontend/src:delegated
      - ./frontend/.env:/frontend/.env:delegated
      - ./frontend/package.json:/frontend/package.json:delegated
    ports:
      - "${FRONTEND_PORT}:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
      - frontend

volumes:
  redis_data:


networks:
  default:
    driver: bridge
